# -*- coding: utf-8 -*-
"""Td_Ifd_Solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10-gt569DgnSvdhNo6lson1AhFhUkl6LG
"""

# Manages on browser file loading,
# not required when run locally

#from google.colab import files

#uploaded = files.upload()

import pandas as pd
import networkx as nx

# Load the data

df = pd.read_csv('./train.csv')

df.info()

print(" No of Rows missing the keyword", df['keyword'].isnull().sum())
print('No of Rows missing the location', df['location'].isnull().sum())

df = df.drop('keyword', axis=1)
df = df.drop('location',axis=1)

display(df.head(5))

import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from bs4 import BeautifulSoup

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('punkt_tab')

lemmatizer = WordNetLemmatizer()

def clean_text(text):

  # Remove URLs
  text = re.sub(r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+','',text)

  # Remove HTML Tags
  text = BeautifulSoup(text, 'html.parser').get_text()

  # Remove emojis
  emoji_pattern = re.compile(
      "["
      "\U0001F600-\U0001F64F"      #Emotions
      "\U0001F300-\U0001F5FF"      #Symbols & Pictographs
      "\U0001F680-\U0001F6FF"      #Transport & Map Symbols
      "\U0001F1E0-\U0001F1FF"      #Flags (iOS)
      "\U00002702-\U000027B0"
      "\U000024C2-\U0001F251"
      "]+", flags=re.UNICODE)
  text = emoji_pattern.sub(r'', text)

  # Remove Punctuation
  text = re.sub(r'[^\w\s]', '', text)

  # Text to lower
  text = text.lower()

  # Remove non-alphanumeric characters
  text = re.sub(r'[^a-zA-Z0-9\s]','', text)

  # Remove numbers
  text = re.sub(r'\d+', '', text)

  # Tokenize the text
  words = nltk.word_tokenize(text)

  # Remove stopwords
  stop_words = set(stopwords.words('english'))

  cleaned_words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words and word.strip() != '']

  # Extra space between quotes is required
  return ' '.join(cleaned_words)

df['text'] = df['text'].apply(clean_text)

clean_df = df.head(5)

display(clean_df)

from sklearn.feature_extraction.text import CountVectorizer

sample_corpora = df['text'].head(2)

count_vectorizer = CountVectorizer()

wm = count_vectorizer.fit_transform(sample_corpora)

# Check the vocabulary to see how words are ordered
print(count_vectorizer.vocabulary_)

doc_names = ['Doc0','Doc1']

feat_names = count_vectorizer.get_feature_names_out()

sample_df = pd.DataFrame(wm.toarray(), index=doc_names, columns=feat_names)

display(sample_df)

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['target'], test_size=0.2, random_state=123)

tfidf_vectorizer = TfidfVectorizer()

tfidf_train_vector = tfidf_vectorizer.fit_transform(X_train, y_train)
tfidf_test_vector = tfidf_vectorizer.transform(X_test)

print('Training vector shape :', tfidf_train_vector.shape)
print('Test vector shape :', tfidf_test_vector.shape)

import numpy as np
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report, f1_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

classifier = RandomForestClassifier(n_estimators=100, random_state=123)

# Split the data into training and testing sets
X_ran_train, X_ran_test, y_ran_train, y_ran_test = train_test_split(tfidf_train_vector, y_train, test_size=0.2, random_state=123)

classifier.fit(X_ran_train, y_ran_train)

y_pred = classifier.predict(X_ran_test)

f1score = f1_score(y_ran_test, y_pred, average='weighted')

print('F1 Score : \n', f1score)

cnf_matrix = confusion_matrix(y_ran_test, y_pred)

print('Confusion Matrix : \n', cnf_matrix)

classification_report = classification_report(y_ran_test, y_pred)

print('Classification Report : \n', classification_report)

#